language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

before_script:
  - echo "Moving to travis-ci.com"
  - rm .env

script:
  - pytest --cov=./

after_success:
  - codecov

env:
  global:
    - secure: "lIQUyD2k1duQdm1z+0z2cUSMwylx+D6b6r8/2vwgT7NtMwFAm0iyVCMNbuL/CzYi6PExdtipdzzlhaGtD5fqcJxD7rQI4FREegJlISX5PNX1CsdLMQPG37RK4k8wzBRvv8wImNU60mZrynOhRHbpIsg7pRqk/F5nGZNr6k9bm0iDPopVLYp2VvQnp4yy0958kMl2eRJ4vY+OhzKbw6HHym4ussVfPQJJuIi6LS6QqORxSF3SRHhxWFYH3JUA+AvW3gP+CMtvnYUT1E8f5nIcB24iq61dolVPmaJei2hmv8P/V9cJlJezaOPJrITy+hwRKkmVP8uSK0l+eVUOiBZfgVDx4R8we+eXQrB/Q1C9db/4Up/y9i4uFYafHHeBUnOZ3nW5dXJB8iNWSAon4Qu9fLzm1C4Zqk+9ZHob/6yPTNGHArwGCYH6bOjiLyv5XD59bshpofE74GDqoShruTeow8mh9j3+z2VcgC8L67GI9EE3YVzC2HrPs28Fm5oXQgOkFOXaqkOGCwiYFQH2OcYHFisp5VM1ZKtDBE08NhzirgcEldzIPDHnYTmLKZqUeNsvmCUy5XGGfYwD6fmBrdOTYWrI1MuxRu8DAw5xzZ6H8qUCvA2Jd79VOGbrKi2mhvPa5Z4+EoxU570y6QGawXDphJoUtP0T8sjJOxz1Lio2/Ls="
    - secure: "pHAwheSFp6UDjO+srp5WtLzt7/rEv9OBoPK1fyzk6/X2JGguSRubKYhGLJpuNql7/6SRklwRfO3vF/Sa7D1+FFsT/Hal2zBfZBnptT6gipL4KMK4K4JLbTSUUG5HxvzRft48gePBVQB5/VwVcFoXWLq2BX0wAe+umFnJhDgDGM/ZTnKKgIR0SkFOmoyQKg452NxmDNF40XpT7ezgXLXsfdJBIbF2gjFpONXqlNqgnXPHom2oZPMortiWPZJ/6KPTJlUQs3p9rpvJztAD+HMWMOti2Igt9+zdKKpfEwuJEbWejoCnqPvfQPiMTaUkxv26Wl0vhk3bmdfn6U4lF5P/tMwINL9fbMeNqawcjQsWF7rNcbDM4qQJnVcDyb93EY5sJBElKrt+3WA/O0SrVlw2L9vYBqbT+1AhAum19zVmtYAJ/GA/41cp4t55nDYXJUjJoMZTceitxZZn/R3Gh/xoPEVayNK7OTzu00h89I89mxwBi6aaHXHy/in7rSAgf84xIxApskBU3UcZuBWCHqjujwzujv4Lvi07j9CtXHvf4PkbcaZnp5UdJiPBEeF4QsJZQF4QNJi1JwaZKYk9EbDW+H6h1APCdCPJ/sJVKb9lGt0Su69vrhfeO4jXhLjEf35za/wdSR28CmiqonylDJKxUUxAp6A/Jo8YJwFJQAu58tY="
    - secure: "hvgQmUyiId8KPyRENmx4A1tZNEm09e5k4rgzBRwrbxdLd6qMy0dKfwMz500E8ap1fKjmmd6MYOd9omWxeex65/TQ7wCY8BFVSmjO3z/av3X+Oxae98wgxs6KrTPc1UkXhWXyvBTDPNRewQc9fKgSzG8YdgOC3j+al9CwkXpUfyzpTTxy247SJtQnkNe/3Dsu1ZOMtBu5x9Ft8cwTQ1dreGiHIL9u2PsyJ3zpBTqBXAzuvXvaY681HSaQGHZn+Yrvwxmt1YVCHlVOd/uD1AMYI1eRP1f2hOPUPYxIOjZboLRuHbd+lSdtGAqP4ovquJT7SrscbkYIq/XEomSMfgI93UF02jzpDSWuJzir93QducQfPKddmyZCtjYBlbiYAyhs1x3RZBKIE0Zfak8PTr4c0lvz9dtkoF9Bt7R1Xp+Tghw8ejPUM9QLc1eNg18wqgjvlAX4bMhq8Ei0K3JdK06EY5A7j2EHh5KSorjd1k2sUuv2ltXJeh02LjrPBUksp+yKa4pNHrMhdmFzFqvCN9EUm5Mzm3urnDTgOX4ktluvVqySlB/gdojK8uHMzZVqajbJBb6N/lrlTwd9qCNtQIx0qaaAvrfqN5QuUKzK5sA351rdkphbxGgVk2nObrbGiGCoWMZXeuxHCPNwM5uA1Wwp1X4gYEibmnJd/B7Wt/rG+/w="
    - secure: "ZLBuJGjK5AmfnnNA5ggD2de590L4sesjldSAZD7G64wOBFUGGV7kP32B0jExLevN82Mi+aBEBka1doXynziZHpENke177Qlbq5WVYin6vxXLbv51/5T9cBTW8xDs2DhQbC1xA87zMqXOyBkFGHISNqd3U3TI+DVxcDZjqKnBU3EK1rbEepyO5dWUsiml6NwxwDQN6zlHz/D5QrY5zv3Y9f77CL6xDYNNNtIwlEaf53UrLx0USKwSq1aZzmrneCQWfD1nNkOCKj2OrTuPhewrAOkjF02WZQB0XyUC/n0O+g1TtGi+1WdsMMDzLincd4qE4z4aXGJzUQEd1KgwIgDgkgRfEDvqMt4VpIGqdva4oYoyZOiTCY9OdjKCu5RL/2CVzBmgCunzFKNNw9+jNfTEAf1E+0GMpTsT6RSbKpq85s/xOL4yQvzIWBCV9YEOZRG/VanNwvwBOrlZVNwbwevFfaP8d5Kqwz++T5SlTqdHsik+JXEEEacUO0ceW89HgUHawkHvWbX1s/fMXFL333Vi2ntFSSjRgd5Buul17JywFqrO3onDEQWQxcr/0e7U/8lyn7Z40CBJQ2UoJK9oz5msVkbR4tC5ieAWgkNMfhbTquK64S5CwRcY0sAq2rydOqQSoDjrbQGCqVHKOEhwrP/78mYHvecUAj046dMlrmTmgRg="
    - secure: "TnQHJorYCuFysLHdzmVIt5lWGHThxHAGku6cBgls3C/ML77QA9tOOyTZvxy8QwEz2lFqPyNTm9rN1fvHXlfUynC28GpHeT3+grHo+GK6RYRZg0eSVTHfA8zSezRac2gNZfG847oUG7Ai5VeJbUQA212pjS96jX1sYJ1ww9CpZ845Ke6qIpiszzyrx9BPfoqzkSJHCkRIvSmI+iGXyauMe5jHStwPsMGAfV8yrPWsMKVGOFTKgWZKjI30g4DLA33K741T8uFjbARQi042trakCKTvLBVrGbQ4E2eRnDAztcdwn/sJ8PtVUTmmbrSFjID0LfEMXOB583fi+p8TzSaSicSwR21NQDlBB2OcaojqZJpvNWgSV/SDOTcgiHFU89EAMK+mTurYjjUssemHPkibJ9eyHLOXB9NFXcFJ7ZuoUkyksEh4L7WDPCmWweA8Hs7QZaOPdxMEIQJNbWcyQfNqlHhx+dkmYsH6aXGahsPlu86edoGPjRYdUcUXXVNxfx4clFrwv+fKptcJqXejW45MLYKDjLouJhHIMZspoy+yoJdpm7s3eGOlFEyegCbWw2r3ZxIqnF4W5g0/ydgoenLwbk+h76zB4nf9HAphoBXyYxT8GUBcwwFXmKKKVsAmFIIZf104CLsvzvwURMpCtXC2JMssLlyyyQyOainP5FsdlIY="
