language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

before_script:
  - rm .env

script:
  - pytest --cov=./

after_success:
  - codecov

env:
  global:
    - secure: "F9QP5dXN9q3s2gQDBEULxQ2JwQoLuscsUFiMWwY3Fqx1hUBRMqsHGgRjfkYQRqRfJOsxcQkzSXNK7hix0EImzcAZVI3e6BZS2X8+fEajuKe0GGkEZ5utGwjWg+HtxQi7+iic10rXdrB35qbrLGUqLfXu+mQxYuDXmpOn7wk+pt0Rx4ESNywqN46OQK8pI+OSA04o8KRZpfFW9ToEC0dbrd80QLhy0YQMIC+xnzXE89rPdQf2HyiKDE9nLacd2784lMoE9rOGi+BMoZbka8RdxulCFemsvcdc3sTa6ynFZu2tLle2uNSxAQOM4TZLh7gCZnEK5RLCzU3U8FwbwA6UcNegy/cW0dwg59cyqpkcEyZ3d7fPbpxO5YUkSHqSL1aleGP7N6y9yLn9nJKLnIIOALlM3rJLmdbdQOLRriZyskdxAy5DcnJEKDO4VlGn7C7DSU5g4QVhgGQzRh5j+8Uk3rr9gLfXbcBwJzxggJZe1IdqHWrt7bqp2WHeZU3WtI2Hg4gdeJCeTiAZHdBfADwavF5f50w32EP16Q4dcW7/GOhWLz3GzcFiMwQdy4DJ/MRCm8RisPP+jEqp2FDhlpo8SP+L9/ry4T+oCCzskR5utCydVmHvRZD53slB4Fp+af80rBRXx67UuLT00fffLRR7M+lkQDB/lsit2Rzr7rH0H+I="
    - secure: "u+8uzbndDbPTroj8wrcwdmRlB35WrG81b0fDlz5RujNqJ2wakmFLvmUvPHKh46KH9kbwM56WJTGByb3vVblGSmW4I8rWj2gehD+gpA0I8MXecraZDFgJCZsJaGo0BOfeJW1nMQWzoivHdJ1Th3+6jRLZ30HvN5NFtFjU0bzi5Qqnov+JLJZfCRBwtPPFBk/Z1nwVJlq1MPykYFI7la/u4C66n03u55cE9EnIUfP9LjWCXgFOOKLVmXI46x/5pDx1Fl9SUk+pltyxjZotgOFeedeGrRBDV6gqBZuVWAHU7jJtlKMAsTMq7q7c9tci3S8DI7J8kqBcUev3i5IggNRY0U6/67N2KLSpuNgtIbgzED/55A4WUmQB580mmg6dPP7w2KP/8Fs37Jv20S6nQa0WZmj0x7+D78HCN/N4pxTa5N3y9wCTXd1qQOL2WaGK3EisB/yjxrl3m6nV1dB5eDFKNjoseZ/OZJ/TfST3BdV3WWqJEQPn3ZhA0dOHTtsynr7DZ9tgk/G5CpUI4Fr7jkCjw4cFtRLaP0cxicx6UkD61llcOfZcYRFXnnbnWXnAGfsMMzU8pLx5C5kAGleNUepvM6wWjoA0kSIwSIl3yDs5q5RbqTiyVuwtq1Bwzm24ukT0y3BvFi/xgdAzHlLIPTY4sh+KTxxsfCLhFHjJStZj244="
    - secure: "i0brHmit5wnUKqXdM8R1s/N2vCjCwTyN/68mkRdpRKEwm52V9Ui1yrPOiRvkoc7a9W6R3Zeme15N8BtRZCLYA2y5aoDHP8173/def3357GeCzjlVR0WPLysymMtV1w16didWRoiQ87lwU5BjPZPjvh1IP+qMzglo4VuOmDGVK5A1buGdcGHfccogJtQfzT9yw6J0eWDhPqfqiI5VQBwti4kvl9iimV1t2Cy4mtjrt2MZhNoi4tKhDTPMGsu5ynoxgXdNHfIbeHbdF9qgh9+fHrC9ntvU/iEsTvX7dIUCszsFt9FMLFU4z6k/7MM7mWxK5tXQw+0JlDJAhK9Bp9oHLj8eQppaZ57RuVv5Fz8V7vBc5GSpLPEm69NCtcWBpfsIb/jVfno7Bj+IEHdt0HcLrOUEcKxZzZ+3SReHyaTzN9bOnMHtgd/2ZSggIbtXIs8NLUhbVbRJbksN+BLF0xv688R4E051owF6xhKJmhXDxGM3Zl/xGtJ5R+D49Z2wEVeQmxMXyxZvRQqN8utBwDxliZEjKXErJVrrpTgj6Olv1CG5GNBnijZlKZz1yJ/+ztGCUKJdQEgEbI+5nmGR2HOLqs0HUwcre3T7oSTenTQArEUKuete6yucZGmEzv4lxkI05swh7tNoK6ZTVRUnzefxmhC6+y81bMXIqbJ93Gcci8E="
    - secure: "cRma8AUX+ickM+8hTbkYKPXTA7K4QYxXoN47mAvXWgRKW0FH/panQiROu9gxA8G428/V04qF9NuS+y6n9pl3f5VarQ+O2DslcG2UgE96jL62iW6I7cR9ExhPyu1GDjPKZILfDqlrDq5LoQQfl4ryt+uKyp4RsqpScAjuCxTdqVc6m6A0ELRchVZBXnALg3fm6PTHt7Hu9yW3+921q+xlKvOSeKe6KQilRUFcuQ/8DbOGzObxHaPNioSN2KnYPSfUYJocA6iSQ/Zj2JnGZWifO/dn70DgGT+lLsQV4X46Juz6/VeaMOsHpLnrJLDPzLPNYEPYABUW28geQ0pQFgHUIolLPs3YUizdau0eF7Oql0nUZaeS0IhTUSuCNW2Syx4kgwP7KDeWPBeGcA8X83E37DEX5WMTPFFO3qop6F1ZaA96VbrLQiu4QDQIGJ11r5U07HeWuCN9Y7w7k8BTzW7Bbl9ach28wex6AJBpjr3BN5NgBjoQi3WhZfKMWjhYGCygQ8zEyEG8frtgCZqjigyWtPOVJ56OuaGIgKV4VyMO7odusG8nDxMQ817/bNKY0nqYg/n0T3RBrcjAeYQ4dwI5qoS62Tz1ngnZibPu7uGz8eLc0Fxjp5eBm2sltmAiDRpuTcICj5ApauyJno5mjO7GIC4OJYsNTRqWVphIz0RbslY="
    - secure: "gqsGZxWjh8HsW9xpCXVIidhe7UBzc5oQ/uljylJo7IHJVUb0C1Ad11b6JSsbQ9GgqkSNDOUJMB8h+JczvV6pBiReC9O+VhXFnY7OWs2hUxCZfDywt3Xsc4Lu3mnkLpfWxl6Oq5+XDNl2kEYys23DR23EB8LMAPEbnsLLM4774K0Mgcgro+FPy+jZv4IMnaC+qH07GH9WT3bCoYlL6Lp7L/q76SmT2++OxEfrV8Yf/Bpo9K9p8nNQTOVhlxCeOH9Uso2VFIrOqVsGzHign5CJfvi9OqEfJT5e8V47hPmgBDLeW9ts2iESXEOFzW8tf9XawSna44LkFjqDrvtcPmrmYC67fCj3UkNjzLDrdAbqqRT6Pfm4Xnfu3RH+tRUhQsLnud3ynEFrE+8d9LPjBmYx606H4leDTbYVMcQAiysO8kJl5I7kKrRYK0uIeoNf+3wg52RmWeCJ+ZCAUvexqhUKHW7+CLYYXTLbSE0kIEsQG2sCu3l8G3J8ucX3bEd6VC1/+VHPwObGl2UuGu9Ry3BJwMFKn7Ar8g9CPWGyh9GrSxvoj/DfDM8aRRqaDn1/5AhRe89ee7BHaLV179l81Gr0xRTn7xkV3zKDRnIf/5a6CoivpTf4vZQMcaI2jVFJHwDPfJnpw1ArMjd4q8V4hFurjyYyk40e6TOKNfmxQwZso0s="
