language: python

python:
  - 3.7
  - 3.8
  - 3.9
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

script: 
  - pytest --cov=./

after_success: 
  - codecov
