language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

before_script:
  - rm .env

script:
  - pytest --cov=./

after_success:
  - codecov

env:
  global:
    - secure: "pmcCw1tbWg7gMSHaThF7W1CnAj0U2HbVwdgHqZc9jZoD7Xn6fCvv8Uf85pURRD4H45grMLwdIBxN5D4xmHaxW4nYqFevOrWfOnpVwrmbXdFUEK1WrKwHJlihJ3AHnks0ehjxgnYjf/rl4GeXCHVz1AmPMD5QQuSyPfVY19oRXunXiyDY78JZTugOxobA2gIzBfzSMJ95O6UnIqaQCNH3J+8Lx5HDSkOAX2YbrE3T9EdDgLld3yT2O5tKU0QaVSsA7+Qy6TVws0vS+IEponD4eKkGdP5lc4xP46to/Ie2Fon77EbLmJGYJVMmvCmRfUvmfJRFAk1YTQfzAG+ZQgmjfG0nIq4UNRYEbbBHkloV9rFmnYkc4yWbHCNRNcVbODwB/vAJqxM5sgmrYYnkIX+Z1xmCQUnUN0FkkH2Ssx8BqdnLR1uyCb9oAxR9ME406O8teRnvLtpqCFLhrTW3SXutjfjiIDQNpLvHJDKksPLPCEWgSVcbhzEvHpqPPMrB3AWmmN+0HN595M24LL68MAfWy1qO/Rh3eHNqolbwqwn7suil/6ym3HgFk7+qE/D41Jt5sOYX8u6OfawxSCM7MbgKGNZxxlzBBliWl4gN9wkingOjKpg8LtjgNSbBRxVBF0r++hl5ERviRMYQhNXe+zQZ5yldngl+BceLrQxTZdivrFw="
    - secure: "OJ7ezW/hMWGKtKRX0k7X2jK8cmHUbHmTSajKuSbB1/3Nl7RJ//S/qD/n0+SoNtvTeyTRFY6XYvhRuDpMrJJTMym5/oKto9M1TgHSDPGdYeXu4ogEnlpDKSJZZvb9+eFGbTLqCiRuMMAjPZ5d9e8M+WhvUEBWaQC/BxfNHTMImtB5k9cQpyO+n6fHATHlPseEfHQanhPooGXM0lbTPy1uWFAjnFZCfqNCQupTIYEGwwYK5mJKm0S1QuMiX7Sv49Jk6x4Klt+dPwXoQnIEs9o/GxvxMcUr6tdcUW/557uVwbpDo1f2YXk6VQnkOLgbf6vImcyUvIlWZPZSpXJ4dwY6pNbzNoyNlQvzoWyhKR/yXBkd5oNsplzhKBdqJavAwr7GdQjNqIF2RpY3kt3AafDP26zCCbpOnfp/VZSrWeLtgIlU/+xaa4ETZwLTMFjM2JvRG3seSZ3H3SL+BWzh3dPDDX2qV0hqoKNkNeWeo1BW7ar2BTvy5SIzm7EudzEVthcsWCajLU6K16EQNlCyFqutKDu29sy2WRWpxLpCcw8ZG8IWmASvI20tFz0N2is5ePqy5Jv3XugJZHaxlw3jfO28B6jr62C4r2KhEqtSjW/R/BUfiyBqP7j3V6pLc8ru5AIAP3gPR4cbc3S7TLbn4veM4kaQwztgblGoFOWOLEv1i30="
    - secure: "Hd5R/ZbjXgsfYoF1hc90REmz/lM91+ObpPSPAiMWcBTbfcYsk0CB/O1sTZJmw4I8d6T3ua1lNeD6SjcXcrPXXJU+7UZ8hmyyCA/xBzHNkTcMT1cm0m6Ov7DJeYt5eDsZ9uIhG9H3jMchTIljxgzSh/fh1nNpZecG9ot92lhBIk8wQKS0hohZDb//KmgOfNdvykg6je5sUwCPy/NvTqLxi9dfGS6yxWXh87iZ7bGwuNU0ORjwXlQB/H+hjZAhQjXZMq2pXrdRVOt+YrbpHXoEDfsOAo3oZKg3uWJNapEazqOYpCLrF7xTcwAG20aslhUGS2JMH6Rretuh70Uw2MY/EIfGs4QioX0gQJDjksb0m01ZvdY28QNe4xi48WUKlJov3G3FhX7zDvXDV9ium2uYUO4YS+HdlR9NADIzY/H/kB7ucytU1C4sAUeFNNdb8mtdUv2rHeGH8KweYOQtS8F/u07Ln023MEMHbQO9xAFKi/je2j1ifItrmmsQKVhV4N7oKVgO3dQYTwCZ0epnImq8AHZTE6nFhxYx+bX9chT5TQYs0EYBvdjjRcGcbp7piHK6HPDwLf0c11H+82xhnWJhTPDd1U2O6gJWOnszXajSOo9uEy/0zOM0h5tUWEiUqjByh6YUKlWwKTJ1EDIhGDQBjGTtKhdthtcMNdUfi/YTjac="
    - secure: "aOUPtGh+W+7AjkEFgu31hoQGIBYBlEBJWduyI/ES8zeLCUn5sdzaOKZdclHZ4IqChKxdk2UtJMdbwP/6+80CtMcBC55Aq2cFPnZlJUNVjbreyzgvomTrIejIkmHVLxfLx5+gcPVj47x8Eh5W1LpaHvOmt/kkhH4Tbo60k58nFGHDCtosvEsD9jN/1RAVX5kzEx1OTbRyTUgo4nDMa5PHcLcq4+APmnO2qSHgxDcCpV+42AegxYShWJVS2EHdif6StMMg9mwLXRkeGV9yQkpNplMEb1nqla3lIVtGyQEAKx5VkBCFNoIWY5IYEUgjS9fv2GwrC6eAJRw4gVlYFTb9i06WTn6whk3hMBvQ867FmN9iDkvfsi6VP9eaLf7PLyfgNZdRHj07UFXapvYRvX0VmQFa/5yjXqNMckClNpXf7922SDU98kApxBrCvFuU7mY4YgLcCRh/BFSzDbA7aWmyXvYKN9UoLUwX3HaHe7gsZnR4wUKXL/8lXwY+vy1dhuW8QLOCcnd8lEs36ndgQNb+5sYHwD1xDO+jyBpF+q5RevGpa6V/wPdNQNIweCdpyTujRLz+3RBgoa5qK8JDn72SC7INmIVIZvvoA1stwYg+sdDBTELawhQLDU9g3Op62OfhJGrbjS/3ibxFdt9eIoYZdZQOnwxXVqYpQWBR8kYsEqE="
    - secure: "TDspPFIkh/3uBnh0p85cg++QM53yO7r2NRJmno49C6TVROPPo5X6ALy4cymCGxn99JkAygPIpoZ7JXdbPXlaEKI9NmGjVtDXIaNd07TdHtD1ngdsOTCHTOg44PWWzoBcdeMjNJGIpJ1VuwOEt1LYEmzVCVp3PdJzdCWFpX9/AeGdsYNo32yE5HekzBuqusUn5lllZsAueM6HzvihX9HINuYpCIJpZ2HLR98uRFjMPt06tpHFoAxyiZmh3ZGQ9BlaU8ow9gY6T1W0cULQe60Ygz+7OgJ3J6Y12HJSrfWjj4/fl9KIzEvYjAsKJdKemhg37KprawIWTpmnb9n/6VdOYYzf1SlW/UVLhOkK3yTj4TosZqRnXgZPJ2vE+ym8st/TOBHgJnLD9fbHhSuy5vR8ulM7W8o/1gTsQG2Nnon81riLE6nl77XvHFUmGSyimDMjEx4uoqhhNs0WUBWMatzmr0MXqgJmQjQbmdqthBBzd41UKH2IuOaWJDwgula00qNJyObcH8t1824cbeWvrsvKz2Sbw1PVN5IE7D3s/c30wiZuNhw3AtmAWDhI+jvrg0P8lKPBrN5Njdv/te5DhQUymZEOxvjo7CQLckpJVC8XwjjqDlBn3h/YSCFLXJJKBRu2YRmeNVcuX2FYuxcSYRnXvNuTeyViDQLa+FTHCoTA8jA="
