language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

before_script:
  - rm .env

script:
  - pytest --cov=./

after_success:
  - codecov

env:
  global:
    - secure: "mfL5loONOnl+XcnJPtD6EI/1Gy6acI9rq56hlKkk0priWHGuufZj0V5GnyUwLtant6bHzSqoHP/KH0FgXnKUmD8szvJhPB1ziqsgNsgJOFzpDpsLqvmI4/aKox3J1G2Bcmz7sxiKfFsKsiu03gRDd2Z2szGVm9TJvk0mQ5UIsH2N44FbXRNbOAfqCdpFgyzPeGIiujYbXAdZo53Ld1tfjOgngJyPv3QhO/SZXE2TnsJglejwwc5O9n08xj+/UBzd/O7Tq6l7LKXv78zR3E7GRk/AEaGP0Y5TMi+c/MgPQbER1XX/JtoQbBFXlYXu5lyYomvvCbFJIz7Yvr+Y1b5Xi0DP0AEN+Ff2IiEX39bZF/x9kydrB0uWLz+DQDwBqP1SefqtrQRWhDm+XR3tRWbcjdlGb12TwEl6ZwlZOElTyppkOMz/wIPAdmufgtdf4WVKxPC15y4VSK3ZkjmO5fGhI+muuGX11TGP7MGVtCcyNsCTFWPY/r9kkXaI7/+/vwoo3/v8GcrpfFYkKroxmQcqMK9rlWMpbZYneZ6VV7gP1kIS7oYTJhqmk6zMslcttTWdG6gBdWP2P/a05j2BEsbvx8hDIxdDqVrl1R8lJA8d9Cnl6BvTM4+F8HYLMQlLTo7mNiKRqyGW1ab0AOCjGPVpLJ+nuouWoYqjewS5SloZ3k8="
    - secure: "MiZoWEsnk2l8UFqnMaSkLcaTKMmpayF7/0xRhcxLXFU04IBkHyyAkYBx9jFRxHTtyIpntZTCx4iG+u32AnhU9pQieH7PVfKuO2ES8NYNUchv51fO88yGWl7MdLf62N20ENAcJUX5bbhHzw+WquwMCS2JtkHdAenCC7jib9FGohudv6DaLEhF5GQioi4UNi/NiTW1g4KJWGXPRyG+XW6PNOL8V262qzi9rxtTHfCj77xbqnFe6jXiZcNX5lqSqGUQ5nSK6qB9nG4WkkoEUmsJscHZqlbPrmR2NeV0yEbcfjYSOELjAcX1+paeVRuw43z0B+bCLWj/oYVPGYcPb2PTjsPtpy3yQk8d55OAosYGPnSUWw3KIC2tG2EOuqntpgYBziNeLg3ryKxvW3olXgf04H8WFmED5ucT7QS0bm9b+DvpzB3oU6PtWyy6Dp1b60DdPJLsAUDr7VaBuRqNcY18TBYaZCSsmdLf+wXEIvG8PRbX2SxxWu2zbxaERfcgJ0+Kokc70Bg5irJv0sbSXWqk4fEJkdmXUpDekLxLV22gqoRCWJXPmdrZANpSvIMyiNW10ERLNaoSQbwZ1o8jBjluR3IV1tPoWlsMaQHgEaa586j3C1eEetEkgFcrrRwlysOBrtbbAEiw2HJwQU2z6011ThhJFZ9M7eQkpM4KF8f6zYE="
    - secure: "beehjpVr/Zb3H6clXNKS8lKyNEUC+W0cdHD5Zhf404O6SGlNsVycFsG8hr6v7rHk8VhEDaYxoYCoBkT4KKx2d3XBVQi7fA4WBvPL6A1Tb7iAq6/S8RnrTNDPUlo10FGLtdMy9rQFRNBBZQeq7aWNeIZT2ykUDCd4QQqmJIoLQkXiTo0A2/6qJIHO5Z11gTPVpGdTyZBFezduVweDw0Dnevw5SNJ7R1rwLSMQwxgqNZIjc9944Z12+E6duK3vsUx1WhbfraNN9079FTNR6nOKlXDrPQlRiLQdsHvqPodOrYszAdRfDZf+R5ZGqbPfyYJOXydYTgjcUcqPHug5ykd2EcnWJGRPw7oA3TBs15oNWjkp4i8KYMhZDtb5eaNWIiaj23vZpLPKTC1HLi/THNlONdAcMr23xzcTghbZNF9hp1Qv2b68305qGs/BTTCuFf0PdLeDVgjLP0CLjGUTd7qhlFLPnKByyMXvKEK1U8twKua3DRRnqSxw+Wt5hTjcL3Cv4apxrYW/ujTXW+l5s19d+czZzw5jGzvlbPcFuKuQFS84xmvcDxodys9jv8K2wOrVV6hBFoifIVOvPyUyY2KmReIyobGFio2TSJRvG5o5c9QERTJCfty2Sa7xbMVS93ty+egW6N+KWn/oR2V2mrMNDS3nYQI5/Z20SaeXWq9iu2o="
    - secure: "nMez6COnhcT4HKc0aIZTsS84D3ypaCie66BiYN24G2gBdNcX2sUh4TCawcktJDwlNeKoH7bPT3AVnkLLpxgnd5d/krrwl58NhdcyLzYhmAcIDwSIDH2RsxLIqF16Cg9pv8mz43EiGXl0rSZxcZAFJrRu2pMGKGDKmCOsV6owRHnBuAsAe1eDhg3mcqOdgPS2o1aQr2s2JKSn3s7hZRp1kJmr2Hezw//vxb8tUuXEHKwG1qTWB71e9wD6MBuHGDUyL7Io7dGOBUn9HqxiqJf5Vm9mrL193tTcBw5atotI9FnJz6gniu/bs8D+eNBx+XNXjWbmgejjTtJooxOhXkFFhrmvXedW4+WODsN1U1u0vHjYts0NiXrGD88zjOKuzdP25BEaokackbUeyTxxXX+Jtothg0ZBMJkTCsXvSAB7hAVP/c1AXOWKb88v2LiP1kHNlrSeFxItwYpndJUrdrtK0FWPMLoUbzne7x/D/EB+gcgIS7z/VN8iQ+9ex0lhkTuJQ6tOQwSpyhYYGgcrNVFdjdn2yMlH7JLLhGb5+M7XzvMlqml8LMw03b3hl0AxR/EbZh4zHx5dXI8oo56q/wzpxNdgiNeyp1wc2aqjI9BtsrnxJH4hBFwojAxtIL5daQHW01w/Sva/4qE5uLfgJQ3KsFxMbxXAoz25Vfn6UEnD6jc="
    - secure: "Av8svo2koCQek+yN5V+OJ2cb9LZ46Z/uihcdV/QjOv3wmHmZAdNN2gEEyS0/kI1gXi0UeAz+eiBKWzHwu4NCOZjG+yIxXRdsRD7nVFAY5jRfvZ93siC35OhT8O32rfA5xgkSWq56Ec7zTVSQGarRh7pN04FJ7V8RbxMoeqWxXafHGMSmEfM4EaaUxdrKK0tybJQlz3/PWajiotGaqQ6OQ7PlpvYqUnUFz5aANxC7OJroWCbbfW2kAib4kfK2b3OFa0ZpedZiY1e0WNIwln/ovlRXLmjgaU+FAaOC4gfUT0KozYgeWFEZdtSDEC9kpkqs9l83lTA/7DntzECks1K/L0/fft1wTovxSJ7Ftalv61wgPjYGe8dGc9VSFuIr2DA47zNUR3BkkJdZNDQAy5lfq5SbtWhzUFYzSoToDlrlcYYIofkskL6DR//alFwt+AaIZHVlunRGMi9+hVLD5dqrGs5ScWnqL3Nc4ulRZGr5LpOEQjl9dNkFeFwFhq9BsBtlFQU8On+UA5b83IrpWOH919XLKY441MIEuRrwRLra1mJbXC4UrhLicvBVaqoZJGgMM+lEsJbrZEotXTXo0I65fDFcRMzrF2pusXLJ5YGaHGZGFNlu9nPJ84m82SfAAJXhVXZeSNn9RzNn/akvQUaJetuJkRkYFoGAKurzNnd/e9Q="
