language: python

python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install -U codecov
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install .

script:
  - rm .env
  - export CLIENT_ID=$CLIENT_ID
  - export CLIENT_SECRET=$CLIENT_SECRET
  - export USER_AGENT=$USER_AGENT
  - export USERNAME=$USERNAME
  - export PASSWORD=$PASSWORD
  - pytest --cov=./

after_success:
  - codecov

env:
  global:
    - secure: PvCspaiqoLfj2xp6LTly1kWnQHQ9jk5Wbu251xpcBgAZ5qTuTd3RmGW11acFy379J0WF++VVm3R5c9ffD/UFQFbxB8DRE5OAR6xmDkvP193b4MmBYeCx6Sj8mkE5oshCjj3tRtKS7oEJIbXZ2Z9KipwWboAUpk6gIaBnuu88iY0x0N6mbCfQCRb04GE/M22TdbWv1aAFlg3oKucQMwNFOxgxaEXB2ZeG7kwruMRKn0D16DRZjDWH8zMe6k91NxMbXs5B5whG52GeidUqlz5x7wYRLButpxEdhdbw0ihm4fgc+g7Oa32gzdwQrVr9I28W4BGcuf/yDfhS8rqAmvfJyBt4O1LIJ9SUEXXCZdDTrFeXOMtSX2vQ1UatqwR6kr4EsPza25vp5v96WIGp0v4FQHUyEJ2zalGq0ZvF1Gm0HA9bv2gtOaA8ioopgHBYqEmXtq+6B5fle7A5L1YjtfbA0WRvnqrvcRJtBVYmSCKxR91oHKTeTKv7fRme8E4fSr7EQ3P2jdHpxKGMoCYlQ++mQN9hXQyasMCQ3Qhv5dHpt3F8ETofdVPGKrJJjwywNHKZRW0IphVHJL2wmSR0PSD+sfWE7JDS0R/fAZUzfBENU7luiIdH+Q7Gl84X6wJTk8K077Dg+0kzmSxzVjUoKk6Rxn8x3QJXQMubdtgLTZY463Q=
    - secure: MZKUzL9djoyFWWJ8huaOgYM5Y6BWfEuNdRm4Z321MIEHYDZX2iUhwzxUZH2khrl2s4k6PJo/x1o6E39AfYiZVNez/cakXodVveeQUj+ocygzJNXB4VvbrQkPW16LI+ej0PSzhQNQdo6AXNQOmUzXO3TL8yOyrCvgmTuhk/auKaMFSMEsugrqmGv1ZzscYIV5nN8UdO8Pll8gmXkkT0KWHfitFZLoaqHuzB3fDozJg1M20RMwEnfN+ADpZ16wLTdurF4ciMLsWnKe2BUXi7QGC+medMFIIQ6iXLjjYPIIiBQuhcZ3+u7LwgaieoN2DA2IA6pPEW2p4OrrxLhUa98fmi1LtPkTqpb0XASXSpaes+dG74E1CPBbEDGRhUQvP3CrHtPP3LeuULoTHonxoCxzZgDCyfDSLGdPLdeZ5x5Zi49/7gP0XQhrrZ9lY6cZl22dWhuwdKvGAyKLs72WwLukighkB+wgTHrmSmCZrxq+wkWI5ak/I+JbGUEI9iGNHzC/VrcNquwc6FtZnohBJSUGdukMgBt2aBGkv2kWlEDcaBlfGH4g76mQLLzMiwS9ltdDnw6YX0dC4DkbXNcX4WW9OzDEXew8X44hmxsN0QoHALa2kPC1Uz3yizzsoWy0DS8uvLJmwSi5I2Ru3Y46w6pVJAMHug4QI6OLKC9vgJscxoI=
    - secure: A3uWxaCeNWfV4VTmS0s/ZVfU3h5ikdmr3IxktReHX9otxMvhTLCgi2CY0gn+r3vHgrjcdNKymEK+o347Lmv4B688VzEtdMAO5qqhkyZ5VrlGtksk7WHkgWQKvemg2sE4FPOdtYHVAQ4XAz9liYl78KHedewFkXIbk61SUu8v1BNZBHdxCRJeeTN66mXhOf71m0cK2f6iFIAHibMozD84btC95V0LjAmo8NUF9L78kJEo7dasqChOgBFctp0U9zFTSLPo6yYz2QY9sGYfgQAKo+ZDWqO3hDmyZAQkH9ntDPj4DpH3f6ivb6aIq886lUMDyr44PbMywzrokNRA8jqmL7wmqnA/QlT/11pzMqOcURq35aFd8+At1kSrtZPvDFSkyJKOdl+Z5zoEpv/Ob6qLdVuI9iRn6zD4r6emmjjCCOHHyP8R+O/b2IBbGuCo03g28VPloCn6HGM80CbcJ7S5Ed7RVuzjcpLL/eUEdVf+VbFo8zX1FH/tlrzdlT0ChTvyWZWredUeEH0uxP3PtZFfq2bfEvac3bqk36KMJU3LqtmMwtxu7wTPPfWRoWeOogm65327CQCFQRYxZjw3BiVzJYK6lnEmTpdJoC9jDxPwreMAYo9z+6vlD1kmYiPMr6njdjkw9XwF9moaOGluUept66PeMR2Aj4bVqV5fqK3QxpI=
    - secure: PumxPTNy7kifh0AkyFyq0igR3+nPZwD6OHoY3ENLD7/cPW/1R6Z3AS9mfLuGZpyOgm6Thx3IvhSvMubKB8fyLmxYp28YP5mvRmxasu4Zj++knqpf47vJeCOhphO+ugncbFUgbHdI4yBCSP2jMSozK8pNMjpoaGbtv7SmpuASGmIKhPhEcsv79OK3gAOKcZ4d7E86wBf7JCn8Fyf5biWdHgEtjb7ytarqB57ANPBQm95hf4lxQ7HDHTxMwQ5R6t2waxYZTVMBOA9w+diEmgFvCMxEuuB8yR8f0Qi8ufvPMbe2pCtG6BjpMxjKYwDm5qpxYUDPmMzUzFGR6G+gZflut8FUGqQ1B8XYd9aPRW5pmD7MKlOQqInWXlSw1xs0knNagzgnthIpUD//w4v3/FVgd8sZythh++v9qWowCSR6fMfC0vyfqBhQpOfcHxFx8a2doNbq4sFw0Axjxn1clNEZcOCNYwaIQn0YCqwmutPpxeINNC2lPjIqsJYjFM6Z/+bg5lYjAvIUahZ9udoXkhFkRoJn7AeOcQfqwtHVNEGXmTFRQQc3MRhmBAiEDGuDu1WLqoJUSGuaqa2YhfoH7Ft1XMDrdhPH/TNviY2/QqJZL5F/8LwIc8lPAEBBRKLX3B2r7E811QLX9ilaThkIj1KczgeRKp8ssd2kTLb826vA9m8=
    - secure: FUYysQhq3yjhxa1G2G4oX+UzIh6l0LMvTtBNTDXFzZY2Qa9NDwS3PGQ9ILfOM4PLGHHI0CkMAHBA2XuAQQTKQT76KZ0aDcM/HjG9cNft2yBxqps258didgRHLWVnPiHqOx2EYMV7jk1AOYFFaVlxgyWvu4+Hw9AZHFiUXTe/PV2hGtCLtNS5i5nY0m5xgG0jL6SPRIE1LLckxvLhtXz5d/b5FoPxFdDN82+tdSC7QI1elqO9x60zIvjMCpXnjd1Vif2yShUe7HgdGvjj6uzFuWW5erc7g7RJD/nAcgXl/OuwgGKlecoUnZiSTJswCF19LXsjMSQPcUcQ2aKveENcVz9nRpXJ3+9goyi+jdqoVMrLDbUge6+6vNXaP6PmkPMmjVUcr2L0nIIdnwpPR++mBsicmGtzXQbyJGSZNnefuFIyYNnXH9ZuCKLwecmmeX0beISBxXt1SOGb7USofmeumn10UPlS+eOswsD4CvpkdK2q+yCUZGIdRIjsoq7OD6SRxX1OTvIQZrjqxJAk7oG1BLVj7VWSiAXiPmZ3UONljGIleHNIiyDkxNGpIzIE9vidtU3SGUsuJUO5oQ2DM/6CmJxotccziJO9U7yTi0FcSfwd4DTg/iAJ4pKtC3OE+CFp/KfjiAPXx27j9xTx7hANd8e8SOBFdIYOk9YF03WX+DI=
