name: Pytest

on: [push, pull_request]
  branches-ignore:
    - 'demo-gifs'
    - 'samples'

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
        
      - name: Install URS
        run: |
          pip install .
      
      - name: Run Pytest
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          pytest --cov=./
            
      - name: Send coverage data to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'
