name: Manual Reddit Scrape

on:
  workflow_dispatch:    # allows manual “Run workflow” presses

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install the URS CLI from PyPI
      - name: Install Universal-Reddit-Scraper (URS)
        run: |
          python -m pip install --upgrade pip
          pip install urs

      # 4) Run the scraper using your custom subreddit list
      - name: Run Reddit Scraper
        env:
          USERNAME:       ${{ secrets.REDDIT_USERNAME }}
          PASSWORD:       ${{ secrets.REDDIT_PASSWORD }}
          CLIENT_ID:      ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET:  ${{ secrets.REDDIT_CLIENT_SECRET }}
          USER_AGENT:     ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          urs -d 1 \
            -s config/subreddits.txt \
            -o output.json

      # 5) Upload output.json so you can download it
      - name: Upload scrape result
        uses: actions/upload-artifact@v4
        with:
          name: reddit_scrape_result
          path: output.json
          retention-days: 7
