name: Manual Reddit Scrape

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout your code
      - uses: actions/checkout@v4

      # 2) setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) install URS as a package
      - name: Install URS
        run: |
          python -m pip install --upgrade pip
          pip install .

      # 4) run the CLI (no urs.py file needed)
      - name: Run Universal-Reddit-Scraper
        env:
          USERNAME:       ${{ secrets.REDDIT_USERNAME }}
          PASSWORD:       ${{ secrets.REDDIT_PASSWORD }}
          CLIENT_ID:      ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET:  ${{ secrets.REDDIT_CLIENT_SECRET }}
          USER_AGENT:     ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          urs -d 1 \
              -s config/subreddits.txt \
              -o output.json

      # 5) upload the JSON for you to download
      - name: Upload scrape result
        uses: actions/upload-artifact@v4
        with:
          name: reddit_scrape_result
          path: output.json
          retention-days: 7
