name: Manual Reddit Scrape

on:
  workflow_dispatch:    # lets you click “Run workflow” manually

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install praw
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Universal-Reddit-Scraper
      env:
        USERNAME:       ${{ secrets.REDDIT_USERNAME }}
        PASSWORD:       ${{ secrets.REDDIT_PASSWORD }}
        CLIENT_ID:      ${{ secrets.REDDIT_CLIENT_ID }}
        CLIENT_SECRET:  ${{ secrets.REDDIT_CLIENT_SECRET }}
        USER_AGENT:     ${{ secrets.REDDIT_USER_AGENT }}
      run: |
        python3 urs/urs.py \
          -d 1 \
          -s config/subreddits.txt \
          -o output.json

    - name: Upload scrape result
      uses: actions/upload-artifact@v4
      with:
        name: reddit_scrape_result
        path: output.json
        retention-days: 7
