name: Manual Reddit scrape
on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install praw
          pip install -r requirements.txt || true  # fallback if file is missing

      - name: Run URS
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python3 urs/urs.py -d 1 -s config/subreddits.txt -o output.json

      - name: Upload scrape result
        uses: actions/upload-artifact@v4
        with:
          name: reddit_scrape_output
          path: output.json
